# this is a test

stages:
  - ğŸ¦„tests
  - ğŸš€deploy

ğŸ¤some-tests:
  only:
    - master
  stage: ğŸ¦„tests
  script:
    - echo "all fine ğŸ˜ƒ"
    #- exit 1 # Failure ğŸ˜¡
    #- exit 0 # Success ğŸ˜ƒ

ğŸš¢go:
  only:
    - master
  stage: ğŸš€deploy
  script:
    - echo "all fine ğŸ˜ƒ ith deployment"
